### ISSUE TITLE
Name Repo

### ISSUE THREAD

**Issue by chelseadoeleman** [techkech/functional-programming-2021#1]
Hi Deanna!

Zou je misschien de naam van je repo naar "functional-programming" kunnen veranderen? 😊
Of bestaat een repo met deze naam al? 

Thanks!

**Comment by techkech** [comment]
hey! ehm, ik heb het probleempje dat m'n eigen account geflagged is vanwege spam (en dus compleet verborgen), ik gok erop dat dit een gevalletje false positive is door github's spam detector. Ik heb gelijk contact opgenomen maar wacht al op een revision sinds vorige week woensdag.. Tot die tijd gebruik ik dit account alleen zodat er iig nog gekeken kan worden naar wat ik aan 't doen ben.

Ik wil zodra ik weer m'n eigen account normaal kan gebruiken, wel weer alles daarheen moven. Ik heb daar al een repo met de naam functional-programming dus ik houd 't liever bij deze reponaam!

**Comment by techkech** [comment]
Duurde ook even voor ik überhaupt dit account+repos omhoog had dus vandaar dat sommige info wat half-assed is anyways
